name: 'DBT_snowflake'
version: '1.0'
profile: 'DBT_snowflake_p1'

# Configuring where dbt will look for different types of files
source-paths: ["models/hr_sample_database"]
target-path: "target"
clean-targets: ["target"]

models:
  your_project_name: 
    schema: 'DBT_SPRUDHVI'
    materialized: Table
