name: 'DBT_snowflake'
version: '1.0'
profile: 'DBT_snowflake_p1'

# Configuring where dbt will look for different types of files
source-paths: ["models/hr_sample_database"]
target-path: "OUTPUT"
clean-targets: ["OUTPUT"]

models:
  your_project_name: 
    schema: 'PUBLIC'
    materialized: view
