your_profile_name: DBT_snowflake_p1
  target: dev
  outputs:
    dev:
      type: snowflake
      account: LK32610
      user: saiprudhvi9127
      password: zicdus-fUwmog-cuqse2
      role: PC_DBT_ROLE
      database: HR_SAMPLE_DATABASE
      warehouse: pc_dbt_wh_large
      schema: DBT_SPRUDHVI
      threads: 1
      client_session_keep_alive: False
